export interface DefaultQuestion {
  ordre: number;
  type: 'qcm' | 'intrus' | 'vraifaux' | 'libre';
  section: string;
  question: string;
  propositions: string[] | null;
  bonne_reponse: string;
  explication?: string;
}

export const defaultQuestions: DefaultQuestion[] = [

  // ══════════════════════════════════════════════════════════════
  // I — VOCABULAIRE (items 1 à 10) — QCM définitions
  // ══════════════════════════════════════════════════════════════

  {
    ordre: 1,
    type: 'qcm',
    section: 'I — Vocabulaire',
    question: 'Quelle est la définition du mot « périgée » ?',
    propositions: [
      'A — Plancher du petit bassin',
      'B — Sans valeur',
      'C — Point de l\'orbite le plus proche de la Terre',
      'D — Contour extérieur',
      'E — Construite',
    ],
    bonne_reponse: 'C — Point de l\'orbite le plus proche de la Terre',
    explication: 'Le périgée est le point de l\'orbite d\'un astre le plus proche de la Terre (ex : le périgée de la Lune).',
  },
  {
    ordre: 2,
    type: 'qcm',
    section: 'I — Vocabulaire',
    question: 'Quelle est la définition du mot « cistre » ?',
    propositions: [
      'A — Luth (instrument à cordes pincées)',
      'B — Arbrisseau',
      'C — Corbeille d\'osier',
      'D — Espèce de courge',
      'E — Brun noirâtre',
    ],
    bonne_reponse: 'A — Luth (instrument à cordes pincées)',
    explication: 'Le cistre est un instrument de musique à cordes pincées, proche du luth, populaire aux XVIe-XVIIe siècles.',
  },
  {
    ordre: 3,
    type: 'qcm',
    section: 'I — Vocabulaire',
    question: 'Quelle est la définition du mot « balane » ?',
    propositions: [
      'A — Fruit',
      'B — Danse',
      'C — Instrument à percussion',
      'D — Crustacé sessile',
      'E — Baume tiré d\'un peuplier',
    ],
    bonne_reponse: 'D — Crustacé sessile',
    explication: 'La balane est un crustacé sessile en forme de cône qui s\'accroche aux rochers et aux coques de bateaux.',
  },
  {
    ordre: 4,
    type: 'qcm',
    section: 'I — Vocabulaire',
    question: 'Quelle est la définition du mot « adret » ?',
    propositions: [
      'A — Ubac',
      'B — Versant ensoleillé',
      'C — Avec adresse',
      'D — Poète grec',
      'E — Tribord',
    ],
    bonne_reponse: 'B — Versant ensoleillé',
    explication: 'L\'adret est le versant d\'une montagne exposé au soleil (vers le sud). Son contraire est l\'ubac.',
  },
  {
    ordre: 5,
    type: 'qcm',
    section: 'I — Vocabulaire',
    question: 'Quelle est la définition du mot « rhizome » ?',
    propositions: [
      'A — Coryza',
      'B — Tige souterraine',
      'C — Méduse',
      'D — Muscle facial',
      'E — Boisson astringente',
    ],
    bonne_reponse: 'B — Tige souterraine',
    explication: 'Le rhizome est une tige souterraine horizontale de certaines plantes (iris, gingembre) permettant leur multiplication.',
  },
  {
    ordre: 6,
    type: 'qcm',
    section: 'I — Vocabulaire',
    question: 'Quelle est la définition du mot « ourlien » ?',
    propositions: [
      'A — Se rapporte à l\'Oural',
      'B — Se rapporte à l\'ourlet',
      'C — Se rapporte à l\'ours',
      'D — Se rapporte à l\'oursin',
      'E — Se rapporte aux oreillons',
    ],
    bonne_reponse: 'E — Se rapporte aux oreillons',
    explication: 'Ourlien est l\'adjectif médical relatif aux oreillons (parotidite ourlienne).',
  },
  {
    ordre: 7,
    type: 'qcm',
    section: 'I — Vocabulaire',
    question: 'Quelle est la définition du mot « dilatoire » ?',
    propositions: [
      'A — Qui gagne du temps',
      'B — Qui augmente le volume',
      'C — Qui fait rire',
      'D — Qui gaspille',
      'E — Qui remplace le dîner',
    ],
    bonne_reponse: 'A — Qui gagne du temps',
    explication: 'Une manœuvre dilatoire sert à retarder, à gagner du temps. Ex : "exception dilatoire" en droit.',
  },
  {
    ordre: 8,
    type: 'qcm',
    section: 'I — Vocabulaire',
    question: 'Quelle est la définition du mot « jas » ?',
    propositions: [
      'A — Roche siliceuse',
      'B — Espèce de vase',
      'C — Mâle de l\'oie',
      'D — Partie d\'une ancre',
      'E — Babil',
    ],
    bonne_reponse: 'D — Partie d\'une ancre',
    explication: 'Le jas est la barre transversale d\'une ancre marine. Terme de marine très spécialisé.',
  },
  {
    ordre: 9,
    type: 'qcm',
    section: 'I — Vocabulaire',
    question: 'Quelle est la définition du mot « hiatus » ?',
    propositions: [
      'A — Affection subite',
      'B — Amas de filets nerveux',
      'C — Interruption / lacune',
      'D — Arbre à fleurs',
      'E — Plante épineuse',
    ],
    bonne_reponse: 'C — Interruption / lacune',
    explication: 'Hiatus : lacune, interruption dans une série. En phonétique : deux voyelles adjacentes sans consonne intermédiaire.',
  },
  {
    ordre: 10,
    type: 'qcm',
    section: 'I — Vocabulaire',
    question: 'Quelle est la définition du mot « relapse » ?',
    propositions: [
      'A — Retombée dans l\'hérésie',
      'B — Remise en liberté',
      'C — Détendue',
      'D — Arrêt',
      'E — Histoire détaillée',
    ],
    bonne_reponse: 'A — Retombée dans l\'hérésie',
    explication: 'Relaps(e) désigne quelqu\'un retombé dans l\'hérésie après l\'avoir abjurée. Terme de droit canonique médiéval.',
  },

  // ══════════════════════════════════════════════════════════════
  // II — CHASSEZ L'INTRUS (items 11 à 20)
  // ══════════════════════════════════════════════════════════════

  {
    ordre: 11,
    type: 'qcm',
    section: 'II — Chassez l\'intrus',
    question: 'Chassez l\'intrus — Ces mots ont une propriété linguistique commune, sauf un :\ngreffe · moule · touriste · manche · mémoire',
    propositions: [
      'A — greffe',
      'B — moule',
      'C — touriste',
      'D — manche',
      'E — mémoire',
    ],
    bonne_reponse: 'C — touriste',
    explication: 'Greffe, moule, manche, mémoire sont des mots polysémiques (plusieurs sens très différents). Touriste n\'a qu\'un sens courant.',
  },
  {
    ordre: 12,
    type: 'qcm',
    section: 'II — Chassez l\'intrus',
    question: 'Chassez l\'intrus — Ces mots sont des pluralia tantum (n\'existent qu\'au pluriel), sauf un :\nobsèques · ténèbres · arrhes · funérailles · vacances',
    propositions: [
      'A — obsèques',
      'B — ténèbres',
      'C — arrhes',
      'D — funérailles',
      'E — vacances',
    ],
    bonne_reponse: 'E — vacances',
    explication: 'Obsèques, ténèbres, arrhes, funérailles sont des pluralia tantum stricts. Vacances a un singulier usuel : "une vacance de poste".',
  },
  {
    ordre: 13,
    type: 'qcm',
    section: 'II — Chassez l\'intrus',
    question: 'Chassez l\'intrus — Ces mots composés sont formés avec verbe + nom, sauf un :\nchou-fleur · brise-glace · pare-boue · porte-monnaie · casse-tête',
    propositions: [
      'A — chou-fleur',
      'B — brise-glace',
      'C — pare-boue',
      'D — porte-monnaie',
      'E — casse-tête',
    ],
    bonne_reponse: 'A — chou-fleur',
    explication: 'Brise-glace, pare-boue, porte-monnaie, casse-tête = verbe + nom. Chou-fleur = nom + nom — c\'est l\'intrus.',
  },
  {
    ordre: 14,
    type: 'qcm',
    section: 'II — Chassez l\'intrus',
    question: 'Chassez l\'intrus — Ces verbes appartiennent au 3e groupe, sauf un :\nrougir · courir · mourir · ouvrir · partir',
    propositions: [
      'A — rougir',
      'B — courir',
      'C — mourir',
      'D — ouvrir',
      'E — partir',
    ],
    bonne_reponse: 'A — rougir',
    explication: 'Courir, mourir, ouvrir, partir = 3e groupe. Rougir = 2e groupe (participe présent : rougissant) — c\'est l\'intrus.',
  },
  {
    ordre: 15,
    type: 'qcm',
    section: 'II — Chassez l\'intrus',
    question: 'Chassez l\'intrus — Ces mots sont des pronoms, sauf un :\ncelle · le mien · chacun · notre · lequel',
    propositions: [
      'A — celle',
      'B — le mien',
      'C — chacun',
      'D — notre',
      'E — lequel',
    ],
    bonne_reponse: 'D — notre',
    explication: 'Celle, le mien, chacun, lequel sont des pronoms. Notre est un adjectif possessif — c\'est l\'intrus.',
  },
  {
    ordre: 16,
    type: 'qcm',
    section: 'II — Chassez l\'intrus',
    question: 'Chassez l\'intrus — Ces mots contiennent la racine ped-/pod- (pied), sauf un :\npodolithe · pédiment · podomètre · pédicule · pédicelle',
    propositions: [
      'A — podolithe',
      'B — pédiment',
      'C — podomètre',
      'D — pédicule',
      'E — pédicelle',
    ],
    bonne_reponse: 'B — pédiment',
    explication: 'Podolithe, podomètre, pédicule, pédicelle contiennent la racine ped-/pod- (pied). Pédiment vient de l\'anglais "pediment" (fronton architectural).',
  },
  {
    ordre: 17,
    type: 'qcm',
    section: 'II — Chassez l\'intrus',
    question: 'Chassez l\'intrus — Ces mots peuvent avoir un pluriel en -aux, sauf un :\ntramail · fermail · chandail · bercail · détail',
    propositions: [
      'A — tramail',
      'B — fermail',
      'C — chandail',
      'D — bercail',
      'E — détail',
    ],
    bonne_reponse: 'B — fermail',
    explication: 'Tramail→tramaux, fermail→fermaux, bercail→bercaux. Chandail→chandails uniquement (pas de forme en -aux).',
  },
  {
    ordre: 18,
    type: 'qcm',
    section: 'II — Chassez l\'intrus',
    question: 'Chassez l\'intrus — Ces mots sont dérivés de « pierre / petra », sauf un :\npierraille · pierreux · pétreux · pierrier · pétrel',
    propositions: [
      'A — pierraille',
      'B — pierreux',
      'C — pétreux',
      'D — pierrier',
      'E — pétrel',
    ],
    bonne_reponse: 'E — pétrel',
    explication: 'Pierraille, pierreux, pétreux, pierrier dérivent de pierre/petra. Le pétrel est un oiseau de mer.',
  },
  {
    ordre: 19,
    type: 'qcm',
    section: 'II — Chassez l\'intrus',
    question: 'Chassez l\'intrus — Ces verbes sont intransitifs (pas de COD), sauf un :\nronfler · dormir · manger · venir · partir',
    propositions: [
      'A — ronfler',
      'B — dormir',
      'C — manger',
      'D — venir',
      'E — partir',
    ],
    bonne_reponse: 'C — manger',
    explication: 'Ronfler, dormir, venir, partir sont intransitifs. Manger est transitif (on mange quelque chose) — c\'est l\'intrus.',
  },
  {
    ordre: 20,
    type: 'qcm',
    section: 'II — Chassez l\'intrus',
    question: 'Chassez l\'intrus — Ces mots sont des adverbes, sauf un :\naussi · volontiers · tôt · parmi · parfois',
    propositions: [
      'A — aussi',
      'B — volontiers',
      'C — tôt',
      'D — parmi',
      'E — parfois',
    ],
    bonne_reponse: 'D — parmi',
    explication: 'Aussi, volontiers, tôt, parfois sont des adverbes. Parmi est une préposition — c\'est l\'intrus.',
  },

  // ══════════════════════════════════════════════════════════════
  // III — CONJUGAISON (items 21 à 30)
  // ══════════════════════════════════════════════════════════════

  {
    ordre: 21,
    type: 'qcm',
    section: 'III — Conjugaison',
    question: 'ACQUÉRIR — Trouvez la forme incorrecte (E si toutes sont correctes) :\nA: acquiers · B: que nous acquérions · C: j\'acquérais · D: tu acquerras',
    propositions: [
      'A — acquiers',
      'B — que nous acquérions',
      'C — j\'acquérais',
      'D — tu acquerras',
      'E — Toutes les formes sont correctes',
    ],
    bonne_reponse: 'E — Toutes les formes sont correctes',
    explication: 'Acquiers (présent), que nous acquérions (subj.), j\'acquérais (imparfait), tu acquerras (futur) — toutes correctes.',
  },
  {
    ordre: 22,
    type: 'qcm',
    section: 'III — Conjugaison',
    question: 'TRESSAILLIR — Trouvez la forme incorrecte :\nA: je tressaillerai · B: qu\'il tressaillît · C: tressaillant · D: nous tressaillons',
    propositions: [
      'A — je tressaillerai',
      'B — qu\'il tressaillît',
      'C — tressaillant',
      'D — nous tressaillons',
      'E — Toutes les formes sont correctes',
    ],
    bonne_reponse: 'A — je tressaillerai',
    explication: 'Le futur correct est "je tressaillirai" (et non tressaillerai). Les formes B, C, D sont correctes.',
  },
  {
    ordre: 23,
    type: 'qcm',
    section: 'III — Conjugaison',
    question: 'VALOIR — Trouvez la forme incorrecte :\nA: valu · B: que nous valions · C: vaux · D: que je vale',
    propositions: [
      'A — valu',
      'B — que nous valions',
      'C — vaux',
      'D — que je vale',
      'E — Toutes les formes sont correctes',
    ],
    bonne_reponse: 'D — que je vale',
    explication: 'Le subjonctif présent de valoir est "que je vaille" (et non "vale"). Valu, que nous valions, vaux sont corrects.',
  },
  {
    ordre: 24,
    type: 'qcm',
    section: 'III — Conjugaison',
    question: 'FUIR — Trouvez la forme incorrecte :\nA: elle fuirait · B: je fuierai · C: fuîtes-vous · D: fui',
    propositions: [
      'A — elle fuirait',
      'B — je fuierai',
      'C — fuîtes-vous',
      'D — fui',
      'E — Toutes les formes sont correctes',
    ],
    bonne_reponse: 'B — je fuirai',
    explication: '"Fuîtes-vous" est incorrect. Le passé simple correct est "vous fuîtes".',
  },
  {
    ordre: 25,
    type: 'qcm',
    section: 'III — Conjugaison',
    question: 'ABSOUDRE — Trouvez la forme incorrecte :\nA: absolu · B: nous absoudrions · C: que j\'absolve · D: il absout',
    propositions: [
      'A — absolu',
      'B — nous absoudrions',
      'C — que j\'absolve',
      'D — il absout',
      'E — Toutes les formes sont correctes',
    ],
    bonne_reponse: 'A — absolu',
    explication: '"Absolu" n\'est pas une forme d\'absoudre — c\'est un adjectif distinct. Le participe passé est "absous/absoute".',
  },
  {
    ordre: 26,
    type: 'qcm',
    section: 'III — Conjugaison',
    question: 'MARTELER — Trouvez la forme incorrecte (E si toutes correctes) :\nA: martelons · B: tu martelles · C: nous aurions martelé · D: que vous marteliez',
    propositions: [
      'A — martelons',
      'B — tu martelles',
      'C — nous aurions martelé',
      'D — que vous marteliez',
      'E — Toutes les formes sont correctes',
    ],
    bonne_reponse: 'B — tu martelles',
    explication: 'Martelons, tu martelles, nous aurions martelé, que vous marteliez sont toutes correctes.',
  },
  {
    ordre: 27,
    type: 'qcm',
    section: 'III — Conjugaison',
    question: 'S\'ASSEOIR — Trouvez la forme incorrecte :\nA: je m\'assieds · B: elles s\'asseyent · C: nous nous assiérons · D: tu t\'assis',
    propositions: [
      'A — je m\'assieds',
      'B — elles s\'asseyent',
      'C — nous nous assiérons',
      'D — tu t\'assis',
      'E — Toutes les formes sont correctes',
    ],
    bonne_reponse: 'E — Toutes les formes sont correctes',
    explication: 'Le futur correct est "nous nous assiérons" ou "nous nous asseyerons". La forme proposée est incorrecte.',
  },
  {
    ordre: 28,
    type: 'qcm',
    section: 'III — Conjugaison',
    question: 'HALETER — Trouvez la forme incorrecte :\nA: haletant · B: j\'halèterai · C: nous halètions · D: elles halètent',
    propositions: [
      'A — haletant',
      'B — j\'halèterai',
      'C — nous halètions',
      'D — elles halètent',
      'E — Toutes les formes sont correctes',
    ],
    bonne_reponse: 'C — nous halètions',
    explication: 'Selon l\'ancienne norme, le futur s\'écrit "j\'halèterai". Forme contestée par les rectifications de 1990.',
  },
  {
    ordre: 29,
    type: 'qcm',
    section: 'III — Conjugaison',
    question: 'RÉVÉLER — Trouvez la forme incorrecte :\nA: je révèle · B: ils révèlent · C: je révélais · D: vous révélerez',
    propositions: [
      'A — je révèle',
      'B — ils révèlent',
      'C — je révélais',
      'D — vous révélerez',
      'E — Toutes les formes sont correctes',
    ],
    bonne_reponse: 'E — Toutes les formes sont correctes',
    explication: 'Selon les rectifications 1990, le futur s\'écrit "vous révèlerez" (accent grave). "Révélerez" avec accent aigu est l\'ancienne norme.',
  },
  {
    ordre: 30,
    type: 'qcm',
    section: 'III — Conjugaison',
    question: 'MOUVOIR — Trouvez la forme incorrecte :\nA: elle meut · B: mû · C: meus · D: je mûs',
    propositions: [
      'A — elle meut',
      'B — mû',
      'C — meus',
      'D — je mûs',
      'E — Toutes les formes sont correctes',
    ],
    bonne_reponse: 'D — je mûs',
    explication: 'Le passé simple de mouvoir est "je mus" sans accent circonflexe. "Je mûs" est incorrect.',
  },

  // ══════════════════════════════════════════════════════════════
  // IV — VRAI OU FAUX (items 31 à 40)
  // ══════════════════════════════════════════════════════════════

  {
    ordre: 31,
    type: 'qcm',
    section: 'IV — Vrai ou Faux',
    question: 'VRAI ou FAUX ?\nL\'énoncé « pas mal, ton histoire » est une litote.',
    propositions: ['A — Vrai', 'B — Faux'],
    bonne_reponse: 'A — Vrai',
    explication: 'Une litote exprime beaucoup en disant peu. "Pas mal" pour "très bien" en est un exemple classique.',
  },
  {
    ordre: 32,
    type: 'qcm',
    section: 'IV — Vrai ou Faux',
    question: 'VRAI ou FAUX ?\nL\'adjectif possessif s\'accorde en personne avec le possesseur de l\'objet possédé.',
    propositions: ['A — Vrai', 'B — Faux'],
    bonne_reponse: 'A — Vrai',
    explication: 'Il s\'accorde en personne/nombre avec le possesseur et en genre/nombre avec le nom accompagné.',
  },
  {
    ordre: 33,
    type: 'qcm',
    section: 'IV — Vrai ou Faux',
    question: 'VRAI ou FAUX ?\n« Une décision a des conséquences » est un syntagme nominal.',
    propositions: ['A — Vrai', 'B — Faux'],
    bonne_reponse: 'B — Faux',
    explication: 'C\'est une phrase verbale. Un syntagme nominal serait : "une décision aux lourdes conséquences".',
  },
  {
    ordre: 34,
    type: 'qcm',
    section: 'IV — Vrai ou Faux',
    question: 'VRAI ou FAUX ?\n« Aucun » est un adjectif numéral cardinal.',
    propositions: ['A — Vrai', 'B — Faux'],
    bonne_reponse: 'B — Faux',
    explication: '"Aucun" est un adjectif indéfini, pas un numéral cardinal.',
  },
  {
    ordre: 35,
    type: 'qcm',
    section: 'IV — Vrai ou Faux',
    question: 'VRAI ou FAUX ?\nUn adjectif qualificatif épithète est toujours antéposé (placé avant le nom).',
    propositions: ['A — Vrai', 'B — Faux'],
    bonne_reponse: 'B — Faux',
    explication: 'Un adjectif épithète peut être antéposé ("belle maison") ou postposé ("maison bleue").',
  },
  {
    ordre: 36,
    type: 'qcm',
    section: 'IV — Vrai ou Faux',
    question: 'VRAI ou FAUX ?\nUn verbe peut former sa conjugaison sur plusieurs radicaux.',
    propositions: ['A — Vrai', 'B — Faux'],
    bonne_reponse: 'A — Vrai',
    explication: 'Ex : aller → vais/allons/iront ; être → suis/sommes/seront.',
  },
  {
    ordre: 37,
    type: 'qcm',
    section: 'IV — Vrai ou Faux',
    question: 'VRAI ou FAUX ?\nL\'énoncé « j\'ai ciré le salon » est une synecdoque.',
    propositions: ['A — Vrai', 'B — Faux'],
    bonne_reponse: 'B — Faux',
    explication: 'C\'est une métonymie (le contenant pour le contenu). La synecdoque désigne un tout par une partie.',
  },
  {
    ordre: 38,
    type: 'qcm',
    section: 'IV — Vrai ou Faux',
    question: 'VRAI ou FAUX ?\nLa langue française écrite utilise un alphabet où l\'on compte 20 consonnes.',
    propositions: ['A — Vrai', 'B — Faux'],
    bonne_reponse: 'A — Vrai',
    explication: '26 lettres = 6 voyelles (a, e, i, o, u, y) + 20 consonnes.',
  },
  {
    ordre: 39,
    type: 'qcm',
    section: 'IV — Vrai ou Faux',
    question: 'VRAI ou FAUX ?\nLe mot « aïeul » commence par le son qui termine le mot « bail ».',
    propositions: ['A — Vrai', 'B — Faux'],
    bonne_reponse: 'A — Vrai',
    explication: '"Bail" se termine par [aj]. "Aïeul" commence par [aj] (le digramme aï).',
  },
  {
    ordre: 40,
    type: 'qcm',
    section: 'IV — Vrai ou Faux',
    question: 'VRAI ou FAUX ?\nDes termes qui assument une même fonction sont en asyndète quand on les juxtapose.',
    propositions: ['A — Vrai', 'B — Faux'],
    bonne_reponse: 'A — Vrai',
    explication: 'L\'asyndète = juxtaposition sans conjonction. Ex : "Il vint, il vit, il vainquit."',
  },

  // ══════════════════════════════════════════════════════════════
  // V — NATURE ET FONCTION (items 41 à 50)
  // ══════════════════════════════════════════════════════════════

  {
    ordre: 41,
    type: 'qcm',
    section: 'V — Nature et Fonction',
    question: 'Quelle est la nature/fonction du mot souligné ?\nJe fais [mienne] cette opinion.',
    propositions: [
      'A — Attribut du sujet',
      'B — Complément d\'objet direct',
      'C — Épithète',
      'D — Attribut du complément d\'objet',
    ],
    bonne_reponse: 'D — Attribut du complément d\'objet',
    explication: '"Mienne" est un pronom possessif, attribut dans la construction "faire sienne".',
  },
  {
    ordre: 42,
    type: 'qcm',
    section: 'V — Nature et Fonction',
    question: 'Quelle est la nature du mot souligné ?\nJ\'[y] reste.',
    propositions: [
      'A — Pronom personnel',
      'B — Pronom indéfini',
      'C — Pronom relatif',
      'D — Pronom personnel',
      'E — Adverbe de lieu',
    ],
    bonne_reponse: 'E — Adverbe de lieu',
    explication: '"Y" est un pronom adverbial de lieu remplaçant "là / dans cet endroit".',
  },
  {
    ordre: 43,
    type: 'qcm',
    section: 'V — Nature et Fonction',
    question: 'Quelle est la nature du mot souligné ?\nIl exercerait bien un [tout] autre travail.',
    propositions: [
      'A — Adverbe',
      'B — Pronom indéfini',
      'C — Adjectif indéfini',
      'D — Adjectif qualificatif',
    ],
    bonne_reponse: 'A — Adverbe',
    explication: '"Tout" devant un adjectif est adverbe (= entièrement). "Tout autre" = entièrement autre.',
  },
  {
    ordre: 44,
    type: 'qcm',
    section: 'V — Nature et Fonction',
    question: 'Quelle est la fonction du mot souligné ?\nCe tapis est mangé aux [mites].',
    propositions: [
      'A — Complément circonstanciel de moyen',
      'B — Complément d\'agent',
      'C — Complément d\'objet direct',
      'D — Complément d\'objet indirect',
    ],
    bonne_reponse: 'B — Complément d\'agent',
    explication: 'Construction passive. Les mites = agent. Reformulation : les mites mangent ce tapis.',
  },
  {
    ordre: 45,
    type: 'qcm',
    section: 'V — Nature et Fonction',
    question: 'Quelle est la nature du mot souligné ?\nJ\'[y] songe.',
    propositions: [
      'A — Adverbe de lieu',
      'B — Pronom personnel',
      'C — Pronom relatif',
      'D — Pronom indéfini',
    ],
    bonne_reponse: 'D — Pronom indéfini',
    explication: '"Y" remplace un COI (je songe à cela → j\'y songe). Pronom personnel COI.',
  },
  {
    ordre: 46,
    type: 'qcm',
    section: 'V — Nature et Fonction',
    question: 'Quelle est la nature du mot souligné ?\n[Que] tu es sage !',
    propositions: [
      'A — Conjonction de subordination',
      'B — Pronom interrogatif',
      'C — Adverbe de quantité',
      'D — Pronom relatif',
    ],
    bonne_reponse: 'C — Adverbe de quantité',
    explication: '"Que" exclamatif = adverbe de quantité (synonyme de "comme"). "Que tu es sage !" = "Comme tu es sage !"',
  },
  {
    ordre: 47,
    type: 'qcm',
    section: 'V — Nature et Fonction',
    question: 'Quelle est la fonction du mot souligné ?\nIl s\'appelle [Arthur].',
    propositions: [
      'A — Attribut du sujet',
      'B — Complément d\'objet direct',
      'C — Complément de manière',
      'D — Apposition',
    ],
    bonne_reponse: 'A — Attribut du sujet',
    explication: '"Arthur" est l\'attribut du sujet "il" via le verbe d\'état "s\'appeler".',
  },
  {
    ordre: 48,
    type: 'qcm',
    section: 'V — Nature et Fonction',
    question: 'Quelle est la fonction du mot souligné ?\nCela marche au [gaz].',
    propositions: [
      'A — Complément d\'agent',
      'B — Complément d\'objet indirect',
      'C — Complément circonstanciel de moyen',
      'D — Complément circonstanciel de manière',
    ],
    bonne_reponse: 'C — Complément circonstanciel de moyen',
    explication: '"Au gaz" indique le moyen de fonctionnement.',
  },
  {
    ordre: 49,
    type: 'qcm',
    section: 'V — Nature et Fonction',
    question: 'Quelle est la nature du mot souligné ?\n[Tel] est mon avis.',
    propositions: [
      'A — Adjectif indéfini',
      'B — Pronom indéfini',
      'C — Adjectif qualificatif',
      'D — Adverbe',
    ],
    bonne_reponse: 'A — Adjectif indéfini',
    explication: '"Tel" est un adjectif indéfini attribut (= de cette sorte).',
  },
  {
    ordre: 50,
    type: 'qcm',
    section: 'V — Nature et Fonction',
    question: 'Quelle est la nature du mot souligné ?\nLa partie et le [tout].',
    propositions: [
      'A — Nom commun',
      'B — Adjectif indéfini',
      'C — Pronom indéfini',
      'D — Adverbe de quantité',
    ],
    bonne_reponse: 'A — Nom commun',
    explication: 'Précédé de "le", tout est nominalisé → nom commun signifiant "la totalité".',
  },

  // ══════════════════════════════════════════════════════════════
  // CULTURE GÉNÉRALE (questions 51 à 60)
  // ══════════════════════════════════════════════════════════════

  {
    ordre: 51,
    type: 'qcm',
    section: 'Culture générale',
    question: 'Le film « La Grande Illusion » a été réalisé par :',
    propositions: ['1 — Orson Welles', '2 — John Ford', '3 — Jean Renoir', '4 — François Truffaut', '5 — Jean-Luc Godard'],
    bonne_reponse: '3 — Jean Renoir',
    explication: '"La Grande Illusion" (1937), chef-d\'œuvre de Jean Renoir sur la Première Guerre mondiale.',
  },
  {
    ordre: 52,
    type: 'qcm',
    section: 'Culture générale',
    question: 'Parmi ces œuvres théâtrales, laquelle n\'est PAS de Molière ?',
    propositions: ['1 — L\'Avare', '2 — Les Plaideurs', '3 — L\'Amour médecin', '4 — Les Précieuses Ridicules', '5 — Le Bourgeois gentilhomme'],
    bonne_reponse: '2 — Les Plaideurs',
    explication: '"Les Plaideurs" est de Jean Racine (1668). Les autres sont bien de Molière.',
  },
  {
    ordre: 53,
    type: 'qcm',
    section: 'Culture générale',
    question: 'Le Soleil est plus volumineux que la Terre. Dans quelle proportion ?',
    propositions: ['1 — 130 fois', '2 — 1 300 fois', '3 — 13 000 fois', '4 — 130 000 fois', '5 — 1 300 000 fois'],
    bonne_reponse: '5 — 1 300 000 fois',
    explication: 'Le Soleil est ~1,3 million de fois plus volumineux (diamètre ×109 → volume ×109³).',
  },
  {
    ordre: 54,
    type: 'qcm',
    section: 'Culture générale',
    question: 'Ludwig van Beethoven a écrit combien de symphonies ?',
    propositions: ['1 — Trois', '2 — Cinq', '3 — Neuf', '4 — Douze', '5 — Vingt'],
    bonne_reponse: '3 — Neuf',
    explication: 'Beethoven a composé 9 symphonies, dont la 5e et la 9e (Ode à la Joie).',
  },
  {
    ordre: 55,
    type: 'qcm',
    section: 'Culture générale',
    question: 'L\'actuel Souverain du Maroc s\'appelle :',
    propositions: ['1 — Abdallah II', '2 — Hassan II', '3 — Mohammed V', '4 — Mohammed VI', '5 — Farouk 1er'],
    bonne_reponse: '4 — Mohammed VI',
    explication: 'Mohammed VI règne depuis 1999, toujours souverain au moment du concours (2005).',
  },
  {
    ordre: 56,
    type: 'qcm',
    section: 'Culture générale',
    question: 'Lequel de ces films n\'est PAS de Hayao Miyazaki ?',
    propositions: ['1 — Nausicaä de la vallée du vent', '2 — Le tombeau des lucioles', '3 — Mon voisin Totoro', '4 — Princesse Mononoké', '5 — Le voyage de Chihiro'],
    bonne_reponse: '2 — Le tombeau des lucioles',
    explication: '"Le tombeau des lucioles" (1988) est de Isao Takahata, pas de Miyazaki.',
  },
  {
    ordre: 57,
    type: 'qcm',
    section: 'Culture générale',
    question: 'Louis Pasteur utilise pour la 1ère fois le vaccin antirabique sur l\'homme :',
    propositions: ['1 — En 1822', '2 — En 1885', '3 — En 1895', '4 — En 1881', '5 — En 1847'],
    bonne_reponse: '2 — En 1885',
    explication: 'Le 6 juillet 1885, Pasteur vaccine Joseph Meister, mordu par un chien enragé.',
  },
  {
    ordre: 58,
    type: 'qcm',
    section: 'Culture générale',
    question: 'L\'épeire est :',
    propositions: ['1 — Une date du calendrier musulman', '2 — Une date du calendrier juif', '3 — Une date du calendrier chrétien', '4 — Une araignée', '5 — Un médicament'],
    bonne_reponse: '4 — Une araignée',
    explication: 'L\'épeire diadème est une araignée très commune en Europe.',
  },
  {
    ordre: 59,
    type: 'qcm',
    section: 'Culture générale',
    question: 'Metz est la Préfecture de :',
    propositions: ['1 — La Moselle', '2 — La Meurthe-et-Moselle', '3 — Le Bas-Rhin', '4 — La Meuse', '5 — L\'Aube'],
    bonne_reponse: '1 — La Moselle',
    explication: 'Metz est la préfecture du département de la Moselle (57), région Grand Est.',
  },
  {
    ordre: 60,
    type: 'qcm',
    section: 'Culture générale',
    question: 'Un cénotaphe est :',
    propositions: ['1 — Un tombeau vide', '2 — Un tombeau contenant une momie', '3 — Un tombeau d\'un Roi', '4 — Un tombeau avec le corps', '5 — Un tombeau avec les cendres'],
    bonne_reponse: '1 — Un tombeau vide',
    explication: 'Un cénotaphe est un monument funéraire ne contenant pas le corps de la personne commémorée.',
  },

  // ══════════════════════════════════════════════════════════════
  // RAISONNEMENT (questions 61 à 70)
  // ══════════════════════════════════════════════════════════════

  {
    ordre: 61,
    type: 'qcm',
    section: 'Raisonnement',
    question: 'Si 7 personnes se rencontrent et que chacune ne serre la main des autres qu\'une seule fois, combien de poignées de main seront échangées ?',
    propositions: ['1 — 6', '2 — 21', '3 — 36', '4 — 42', '5 — 49'],
    bonne_reponse: '2 — 21',
    explication: 'C(7,2) = 7×6/2 = 21.',
  },
  {
    ordre: 62,
    type: 'qcm',
    section: 'Raisonnement',
    question: 'On ajoute 1 mètre à une ficelle faisant le tour de la Terre ET à une ficelle faisant le tour d\'une roue. La ficelle de la roue s\'éloigne-t-elle autant, plus ou moins que celle de la Terre ?',
    propositions: ['1 — Autant', '2 — Plus', '3 — Moins'],
    bonne_reponse: '1 — Autant',
    explication: 'Δrayon = 1/(2π) ≈ 16 cm, quelle que soit la circonférence initiale.',
  },
  {
    ordre: 63,
    type: 'qcm',
    section: 'Raisonnement',
    question: 'Un bouquet de 8 fleurs : 7 tulipes dont 6 rouges. Combien de bouquets différents selon les critères « tulipe » et « rouge » ?',
    propositions: ['1 — 1', '2 — 2', '3 — 4', '4 — On ne peut pas savoir', '5 — 8'],
    bonne_reponse: '3 — 4',
    explication: '4 configurations : tulipes rouges / tulipes non-rouges / non-tulipes rouges / non-tulipes non-rouges.',
  },
  {
    ordre: 64,
    type: 'qcm',
    section: 'Raisonnement',
    question: 'Un microbe double chaque seconde et remplit un pot en 60 secondes. Avec 4 microbes au départ, combien de temps ?',
    propositions: ['1 — 60s', '2 — 30s', '3 — 58s', '4 — 56s', '5 — 15s'],
    bonne_reponse: '3 — 58s',
    explication: '4 = 2² → on gagne 2 secondes. 60 − 2 = 58 secondes.',
  },
  {
    ordre: 65,
    type: 'qcm',
    section: 'Raisonnement',
    question: 'Vol Zing→Setnan : 9h00→13h40. Vol Setnan→Zing : 15h00→21h40.\nL\'horloge de Zing indique Mardi 4 janv. 0h50. Que lit-on sur l\'horloge de Setnan ?',
    propositions: ['1 — Lundi 3/01, 22h50', '2 — Lundi 3/01, 23h50', '3 — Mardi 4/01, 0h50', '4 — Mardi 4/01, 1h50', '5 — Mardi 4/01, 2h50'],
    bonne_reponse: '5 — Mardi 4 janv., 2h50',
    explication: 'Durée A→B = 4h40, B→A = 6h40 → Setnan en avance de 2h. 0h50 + 2h = 2h50.',
  },
  {
    ordre: 66,
    type: 'qcm',
    section: 'Raisonnement',
    question: 'Un takilé fait des sauts de 2,34 m et parcourt 582,66 m en 3 minutes. Combien de sauts par minute ?',
    propositions: ['1 — 249', '2 — 107', '3 — 85', '4 — 83', '5 — 79'],
    bonne_reponse: '4 — 83',
    explication: '582,66 / 2,34 = 249 sauts. 249 / 3 = 83 sauts/min.',
  },
  {
    ordre: 67,
    type: 'qcm',
    section: 'Raisonnement',
    question: 'Un ver parcourt de la 1ère page du vol. 1 à la dernière page du vol. 3 de Molière. Volumes 10 cm, plats 5 mm. Longueur du trajet ?',
    propositions: ['1 — 31 cm', '2 — 22,5 cm', '3 — 12 cm', '4 — 11,5 cm', '5 — Aucune réponse juste'],
    bonne_reponse: '4 — 11,5 cm',
    explication: 'Plat droit vol.1 (5mm) + vol.2 (10cm) + plat gauche vol.3 (5mm) = 11 cm (ou 11,5 cm selon interprétation).',
  },
  {
    ordre: 68,
    type: 'qcm',
    section: 'Raisonnement',
    question: 'Divisez 40 par 1/2 et ajoutez 10. Combien obtenez-vous ?',
    propositions: ['1 — 20', '2 — 30', '3 — 50', '4 — 80', '5 — 90'],
    bonne_reponse: '5 — 90',
    explication: '40 ÷ ½ = 80. 80 + 10 = 90. Diviser par ½ = multiplier par 2 !',
  },
  {
    ordre: 69,
    type: 'qcm',
    section: 'Raisonnement',
    question: 'Âge grand-père ∈ [50,70]. Chaque enfant a autant d\'enfants que de frères/sœurs. Âge = enfants + petits-enfants. Quel âge ?',
    propositions: ['1 — 58 ans', '2 — 60 ans', '3 — 62 ans', '4 — 64 ans', '5 — 68 ans'],
    bonne_reponse: '3 — 62 ans',
    explication: 'Réponse officielle du concours.',
  },
  {
    ordre: 70,
    type: 'qcm',
    section: 'Raisonnement',
    question: 'Boîtes BB, NN, BN (étiquettes toutes fausses, 2 billes/boîte). Peut-on connaître le contenu en tirant une seule bille ?',
    propositions: [
      '1 — Non, il faut tirer 2 billes de BB et NN',
      '2 — Non, il faut tirer 2 billes de BN',
      '3 — Non, il faut 1 bille de BB/NN + 1 de BN',
      '4 — Oui, en tirant de BB ou NN',
      '5 — Oui, en tirant de BN',
    ],
    bonne_reponse: '5 — Oui, en tirant de BN',
    explication: 'La boîte "BN" contient BB ou NN. 1 bille suffit pour tout déduire par élimination.',
  },
];
